### ISSUE TITLE
Erro logo de debugar o plugin

### ISSUE THREAD

**Issue by nicolasfranz** [DevelopersRede/woocommerce#24]
Olá pessoal, estamos achando esse erro no Log, e acreditamos será útil para a comunidade. Usamos a versão mais recente aqui no Git, confere: 

2019-11-05T14:01:02+00:00 CRITICAL Uncaught Error: Call to undefined method WP_Post::get_id() in /home/deslizecom/public_html/wp-content/plugins/rede-woocommerce/rede-woocommerce.php:174
Stack trace:
#0 /home/deslizecom/public_html/wp-includes/class-wp-hook.php(286): update_rede_orders()
#1 /home/deslizecom/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /home/deslizecom/public_html/wp-includes/plugin.php(531): WP_Hook->do_action(Array)
#3 /home/deslizecom/public_html/wp-cron.php(133): do_action_ref_array('update_rede_ord...', Array)
#4 {main}
  thrown, em /home/deslizecom/public_html/wp-content/plugins/rede-woocommerce/rede-woocommerce.php, na linha 174

Um erro grave. Como resolver essa situação?
Espero que seja útil a informação, obrigado!

**Comment by marcos-alexandre82** [comment]
A versão que você está utilizando está com a pasta "vendor" inclusa?

**Comment by g3luka** [comment]
Estou com esse mesmo problema:

CRITICAL Call to undefined method WP_Post::get_id(), em /home/equalisvet/app/plugins/rede-woocommerce/rede-woocommerce.php, na linha 175

Sim, está com a pasta vendor inclusa.

**Comment by marcos-alexandre82** [comment]
@g3luka e @nicolasfranz , já testaram a última versão que está no meu repositório?
https://github.com/marcos-alexandre82/woocommerce/tree/develop

Nela tem alguns ajustes que estou aguardando serem aceitos aqui, mas estou utilizando em um cliente e não tivemos estes erros.

Se puderem (caso ainda não estejam utilizando) testar em um ambiente de homologação e reportar aqui se está tudo certo ou com algum erro, agradecemos ;)
